# Generated by Django 4.2 on 2023-05-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_likedposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_With_Tags',
            new_name='PostWithTags',
        ),
    ]
