# Generated by Django 4.2 on 2023-05-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0005_rename_post_with_tags_postwithtags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DifficultyLevel',
        ),
    ]
